[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aions-llm"
version = "1.0.12"
authors = [
  { name="Sourav Modak" },
]
description = "Actions and Interface Object Notation: An open standard for LLM tools."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "langchain>=0.1.0",
]

[tool.setuptools.packages.find]
where = ["src"]